### PR TITLE
Explore new table

### PR DESCRIPTION
**Pull request by pierrepo**

### CODE REVIEW

**Comment by pierrepo** [comment]
@Moohmoo the table doesn't show up in the app. Is there any specific action to perform?

**Comment by Moohmoo** [comment]
@pierrepo If all packages are downloaded and updated, there is normally no problem. I will check.

**Comment by Moohmoo** [comment]
@pierrepo I just fixed the problem, it was a version compatibility problem between bokeh and streamlit-bokeh-events. I make some modifications and the merge can be done.

**Comment by Moohmoo** [comment]
@pierrepo Can you take a look at my code? I will take care of the conflicting files when I have your approval.

**Comment by pierrepo** [comment]
@Moohmoo this looks very nice. Thanks.

There is however a small bug with the table selection. It is indeed reflected in the left panel with all the details, but the "Export" button exports all data in the table not the ones that are selected by multiple clicks on the left of the table.

Could you have a look at it, please?

**Comment by Moohmoo** [comment]
@pierrepo I solved the problem it was just because of a variable assignment. I make some modifications and I will wait for your confirmation to fix the conflicts and to make a merge.

**Pull request merged**
